# frozen_string_literal: true

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "bin/**/*"
    - "scratch.rb"

# Layout
Layout/LineLength:
  Max: 120
  AllowedPatterns: ['\A\s*#']

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/Lambda:
  EnforcedStyle: literal

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/NumericLiterals:
  MinDigits: 5

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: compact

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

# Metrics
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
    - "examples/**/*"

Metrics/MethodLength:
  Max: 25
  CountAsOne: ["array", "heredoc"]

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 25

# Naming
Naming/PredicateName:
  ForbiddenPrefixes: ["is_"]
  AllowedMethods: ["is_a?"]

# Lint
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

# Performance
Performance/StringReplacement:
  Enabled: true

# RSpec specific (when using rubocop-rspec)
RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - "spec/integration/**/*"

# Minitest specific (when using rubocop-minitest)
Minitest/MultipleAssertions:
  Max: 5

Minitest/AssertionInLoop:
  Enabled: false
